top = "."

out = "build"


def configure(ctx):
    try:
        ctx.find_program('touch', var='TOUCH')
    except ctx.errors.ConfigurationError:
        ctx.to_log('touch was not found (ignoring)')
    print('→ configuring the project in ' + ctx.path.abspath())
    print(f" the vlaue of foo is {ctx.options.foo}")


def options(ctx):
    ctx.add_option('--foo', action='store', default=False, help='Silly test')


def hello(ctx):
    print('Hello from WAF!!')


def ping(ctx):
    print(' ping! %d' % id(ctx))


def pong(ctx):
    print(' pong! %d' % id(ctx))


def idowhatiwant(ctx):
    print("Deep down low.")
